colour_schemes = [
    {'main': 'purple',
     'second': 'black',
     'background': 'orange'},
    {'main': '#292F3D',
     'second': 'white',
     'background': '#008DD5'},
    {'main': '#DAFEB7',
     'second': '#F2FBE0',
     'background': '#605B56'},
    {'main': '#0F4C5C',
     'second': '#111111',
     'background': '#FB8B24'},
    {'main': '#23395B',
     'second': '#406E8E',
     'background': '#CBF7ED'},
    {'main': '#E3B5A4',
     'second': '#F5E9E2',
     'background': '#0B0014'},
    {'main': '#55286F',
     'second': '#1A281F',
     'background': '#DEFFFC'},
]